#!/bin/sh
set -e -u -o pipefail

set -- "$@" '--config' "/app/ovpn/vpntunnel/${REGION:-sweden}.ovpn"

if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
	echo "$USERNAME" > auth.conf
	echo "$PASSWORD" >> auth.conf
	chmod 600 auth.conf
	set -- "$@" '--auth-user-pass' 'auth.conf'
else
	echo "OpenVPN credentials not set. Exiting."
	exit 1
fi

openvpn "$@" --auth-nocache --script-security 3 --up "/app/sockd.sh"
